DROP DATABASE IF EXISTS guessthenumberdb;
CREATE DATABASE guessthenumberdb;

USE guessthenumberdb;

CREATE TABLE game(
gameId INT PRIMARY KEY AUTO_INCREMENT,
gameAnswer VARCHAR(4) NOT NULL,
gameStatus VARCHAR(15) DEFAULT 'In Progress');

CREATE TABLE round(
roundId INT PRIMARY KEY AUTO_INCREMENT,
guess VARCHAR(4) NOT NULL,
guessTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
roundResult VARCHAR(10) NOT NULL,
gameId INT NOT NULL,
FOREIGN KEY (gameId) REFERENCES game(gameId));